matrix:
  include:
    - language: cpp
      compiler:
        - gcc
      install:
        - "[ $CXX = g++ ] && export CXX=g++-6 || true"
      script:
        - bash test_cpp.sh

    - language: python
      python: 3.7
      before_script:
        - cd Python/tests/problems
      script:
        - python -m unittest discover

sudo: false
addons:
  sonarcloud:
    organization: "walterjgsp-github" # the key of the org you chose at step #3
    token: $SONAR_TOKEN
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
